import {v2 as cloudinary} from 'cloudinary'

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME, 
  api_key: process.env.CLOUDINARY_API_KEY, 
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true
})

export const uploadImage = async (filePath) => {
  console.log("entro")
  return new Promise((resolve, reject) => {
    cloudinary.uploader.upload(filePath, (err, url) => {
      if (err) return reject(err);
      return resolve(url);
    })
  });
  
  /* 
  try {
    const result = cloudinary.uploader.upload(filePath, { 
      folder: 'zular',
      async: true
    })
    console.log();
    console.log("** File Upload");
    console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
    console.log("* " + result.public_id);
    console.log("* " + result.url);
    
    return result
  } 
  catch (err) {
    console.error(err);
  }
  */
}

export const deleteImage = async (public_id) => {
  return await cloudinary.uploader.destroy(public_id, function (err, image) {
    console.log();
    console.log("** File Deleted");
    if (err) { console.error(err); }
    console.log(`* file with public_id: ${public_id} has been deleted Cloudinary's service.`);
  })
}